databases:
  - name: ruby-blog
    databaseName: ruby-blog
    user: ruby-blog
    plan: free

services:
  - type: web
    name: ruby-blog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby-blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: a1d7f823bf6415b093b2746fe47f681d
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: RAILS_ENV
        value: production
